# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dongyubo/cmake-3.22.0-rc3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/dongyubo/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dongyubo/桌面/Compiler/our_compiler/carolcc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dongyubo/桌面/Compiler/our_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/dongyubo/cmake-3.22.0-rc3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dongyubo/cmake-3.22.0-rc3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dongyubo/桌面/Compiler/our_compiler/CMakeFiles /home/dongyubo/桌面/Compiler/our_compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dongyubo/桌面/Compiler/our_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

src/frontend/parser.o: src/frontend/parser.cpp.o
.PHONY : src/frontend/parser.o

# target to build an object file
src/frontend/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/parser.cpp.o
.PHONY : src/frontend/parser.cpp.o

src/frontend/parser.i: src/frontend/parser.cpp.i
.PHONY : src/frontend/parser.i

# target to preprocess a source file
src/frontend/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/parser.cpp.i
.PHONY : src/frontend/parser.cpp.i

src/frontend/parser.s: src/frontend/parser.cpp.s
.PHONY : src/frontend/parser.s

# target to generate assembly for a file
src/frontend/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/parser.cpp.s
.PHONY : src/frontend/parser.cpp.s

src/frontend/token.o: src/frontend/token.cpp.o
.PHONY : src/frontend/token.o

# target to build an object file
src/frontend/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/token.cpp.o
.PHONY : src/frontend/token.cpp.o

src/frontend/token.i: src/frontend/token.cpp.i
.PHONY : src/frontend/token.i

# target to preprocess a source file
src/frontend/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/token.cpp.i
.PHONY : src/frontend/token.cpp.i

src/frontend/token.s: src/frontend/token.cpp.s
.PHONY : src/frontend/token.s

# target to generate assembly for a file
src/frontend/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/frontend/token.cpp.s
.PHONY : src/frontend/token.cpp.s

src/helpers/graph_helper.o: src/helpers/graph_helper.cpp.o
.PHONY : src/helpers/graph_helper.o

# target to build an object file
src/helpers/graph_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/graph_helper.cpp.o
.PHONY : src/helpers/graph_helper.cpp.o

src/helpers/graph_helper.i: src/helpers/graph_helper.cpp.i
.PHONY : src/helpers/graph_helper.i

# target to preprocess a source file
src/helpers/graph_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/graph_helper.cpp.i
.PHONY : src/helpers/graph_helper.cpp.i

src/helpers/graph_helper.s: src/helpers/graph_helper.cpp.s
.PHONY : src/helpers/graph_helper.s

# target to generate assembly for a file
src/helpers/graph_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/graph_helper.cpp.s
.PHONY : src/helpers/graph_helper.cpp.s

src/helpers/type_helper.o: src/helpers/type_helper.cpp.o
.PHONY : src/helpers/type_helper.o

# target to build an object file
src/helpers/type_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/type_helper.cpp.o
.PHONY : src/helpers/type_helper.cpp.o

src/helpers/type_helper.i: src/helpers/type_helper.cpp.i
.PHONY : src/helpers/type_helper.i

# target to preprocess a source file
src/helpers/type_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/type_helper.cpp.i
.PHONY : src/helpers/type_helper.cpp.i

src/helpers/type_helper.s: src/helpers/type_helper.cpp.s
.PHONY : src/helpers/type_helper.s

# target to generate assembly for a file
src/helpers/type_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/helpers/type_helper.cpp.s
.PHONY : src/helpers/type_helper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/runtime.o: src/runtime.cpp.o
.PHONY : src/runtime.o

# target to build an object file
src/runtime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/runtime.cpp.o
.PHONY : src/runtime.cpp.o

src/runtime.i: src/runtime.cpp.i
.PHONY : src/runtime.i

# target to preprocess a source file
src/runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/runtime.cpp.i
.PHONY : src/runtime.cpp.i

src/runtime.s: src/runtime.cpp.s
.PHONY : src/runtime.s

# target to generate assembly for a file
src/runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/runtime.cpp.s
.PHONY : src/runtime.cpp.s

src/syntax_tree.o: src/syntax_tree.cpp.o
.PHONY : src/syntax_tree.o

# target to build an object file
src/syntax_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/syntax_tree.cpp.o
.PHONY : src/syntax_tree.cpp.o

src/syntax_tree.i: src/syntax_tree.cpp.i
.PHONY : src/syntax_tree.i

# target to preprocess a source file
src/syntax_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/syntax_tree.cpp.i
.PHONY : src/syntax_tree.cpp.i

src/syntax_tree.s: src/syntax_tree.cpp.s
.PHONY : src/syntax_tree.s

# target to generate assembly for a file
src/syntax_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/syntax_tree.cpp.s
.PHONY : src/syntax_tree.cpp.s

src/visitor/syntax_detail_shower.o: src/visitor/syntax_detail_shower.cpp.o
.PHONY : src/visitor/syntax_detail_shower.o

# target to build an object file
src/visitor/syntax_detail_shower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_detail_shower.cpp.o
.PHONY : src/visitor/syntax_detail_shower.cpp.o

src/visitor/syntax_detail_shower.i: src/visitor/syntax_detail_shower.cpp.i
.PHONY : src/visitor/syntax_detail_shower.i

# target to preprocess a source file
src/visitor/syntax_detail_shower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_detail_shower.cpp.i
.PHONY : src/visitor/syntax_detail_shower.cpp.i

src/visitor/syntax_detail_shower.s: src/visitor/syntax_detail_shower.cpp.s
.PHONY : src/visitor/syntax_detail_shower.s

# target to generate assembly for a file
src/visitor/syntax_detail_shower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_detail_shower.cpp.s
.PHONY : src/visitor/syntax_detail_shower.cpp.s

src/visitor/syntax_tree_builder.o: src/visitor/syntax_tree_builder.cpp.o
.PHONY : src/visitor/syntax_tree_builder.o

# target to build an object file
src/visitor/syntax_tree_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_builder.cpp.o
.PHONY : src/visitor/syntax_tree_builder.cpp.o

src/visitor/syntax_tree_builder.i: src/visitor/syntax_tree_builder.cpp.i
.PHONY : src/visitor/syntax_tree_builder.i

# target to preprocess a source file
src/visitor/syntax_tree_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_builder.cpp.i
.PHONY : src/visitor/syntax_tree_builder.cpp.i

src/visitor/syntax_tree_builder.s: src/visitor/syntax_tree_builder.cpp.s
.PHONY : src/visitor/syntax_tree_builder.s

# target to generate assembly for a file
src/visitor/syntax_tree_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_builder.cpp.s
.PHONY : src/visitor/syntax_tree_builder.cpp.s

src/visitor/syntax_tree_shower.o: src/visitor/syntax_tree_shower.cpp.o
.PHONY : src/visitor/syntax_tree_shower.o

# target to build an object file
src/visitor/syntax_tree_shower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_shower.cpp.o
.PHONY : src/visitor/syntax_tree_shower.cpp.o

src/visitor/syntax_tree_shower.i: src/visitor/syntax_tree_shower.cpp.i
.PHONY : src/visitor/syntax_tree_shower.i

# target to preprocess a source file
src/visitor/syntax_tree_shower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_shower.cpp.i
.PHONY : src/visitor/syntax_tree_shower.cpp.i

src/visitor/syntax_tree_shower.s: src/visitor/syntax_tree_shower.cpp.s
.PHONY : src/visitor/syntax_tree_shower.s

# target to generate assembly for a file
src/visitor/syntax_tree_shower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/syntax_tree_shower.cpp.s
.PHONY : src/visitor/syntax_tree_shower.cpp.s

src/visitor/visitor_base.o: src/visitor/visitor_base.cpp.o
.PHONY : src/visitor/visitor_base.o

# target to build an object file
src/visitor/visitor_base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/visitor_base.cpp.o
.PHONY : src/visitor/visitor_base.cpp.o

src/visitor/visitor_base.i: src/visitor/visitor_base.cpp.i
.PHONY : src/visitor/visitor_base.i

# target to preprocess a source file
src/visitor/visitor_base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/visitor_base.cpp.i
.PHONY : src/visitor/visitor_base.cpp.i

src/visitor/visitor_base.s: src/visitor/visitor_base.cpp.s
.PHONY : src/visitor/visitor_base.s

# target to generate assembly for a file
src/visitor/visitor_base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/visitor/visitor_base.cpp.s
.PHONY : src/visitor/visitor_base.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compiler"
	@echo "... src/frontend/parser.o"
	@echo "... src/frontend/parser.i"
	@echo "... src/frontend/parser.s"
	@echo "... src/frontend/token.o"
	@echo "... src/frontend/token.i"
	@echo "... src/frontend/token.s"
	@echo "... src/helpers/graph_helper.o"
	@echo "... src/helpers/graph_helper.i"
	@echo "... src/helpers/graph_helper.s"
	@echo "... src/helpers/type_helper.o"
	@echo "... src/helpers/type_helper.i"
	@echo "... src/helpers/type_helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/runtime.o"
	@echo "... src/runtime.i"
	@echo "... src/runtime.s"
	@echo "... src/syntax_tree.o"
	@echo "... src/syntax_tree.i"
	@echo "... src/syntax_tree.s"
	@echo "... src/visitor/syntax_detail_shower.o"
	@echo "... src/visitor/syntax_detail_shower.i"
	@echo "... src/visitor/syntax_detail_shower.s"
	@echo "... src/visitor/syntax_tree_builder.o"
	@echo "... src/visitor/syntax_tree_builder.i"
	@echo "... src/visitor/syntax_tree_builder.s"
	@echo "... src/visitor/syntax_tree_shower.o"
	@echo "... src/visitor/syntax_tree_shower.i"
	@echo "... src/visitor/syntax_tree_shower.s"
	@echo "... src/visitor/visitor_base.o"
	@echo "... src/visitor/visitor_base.i"
	@echo "... src/visitor/visitor_base.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

